# Generated by Django 4.2.13 on 2024-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Чат ID пользователя'),
        ),
    ]
